---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish packages

on:
  push:
    tags: ["*"]

permissions: {}

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@552942537a2a9ce245fbfabeb89829adfb773506
    permissions:
      contents: write # create github release
      id-token: write # deploy
      attestations: write # create attestations
    with:
      abi-version: "15"
      generate: false
      attestations: true
  crates:
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@552942537a2a9ce245fbfabeb89829adfb773506
    permissions:
      id-token: write # deploy
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    with:
      abi-version: "15"
      generate: false
  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@552942537a2a9ce245fbfabeb89829adfb773506
    permissions:
      id-token: write # deploy
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    with:
      abi-version: "15"
      generate: false
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@552942537a2a9ce245fbfabeb89829adfb773506
    permissions:
      id-token: write # deploy
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    with:
      abi-version: "15"
      generate: false
